name       : img2pdf
version    : 0.4.2
release    : 6
source     :
    - https://gitlab.mister-muffin.de/josch/img2pdf/archive/0.4.2.tar.gz : 43ede50151ba8e1422c0d2e9e2bc3deb57a21bd017c9018c141dcfa71f2b85fe
homepage   : https://gitlab.mister-muffin.de/josch/img2pdf
license    : LGPL-3.0-or-later
component  : multimedia.graphics
summary    : Losslessly convert raster images to PDF
description: |
    Python 3 library and command line utility img2pdf for losslessly converting a bunch of image files into a PDF file. That means that the images are either inserted into the PDF as-is or they are recompressed using lossless compression. Thus, img2pdf usually runs faster and may yield smaller PDF files than an ImageMagick convert command.
rundeps    :
    - python-pikepdf
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -f $installdir/usr/bin/img2pdf-gui
