name       : img2pdf
version    : 0.3.6
release    : 1
source     :
    - https://pypi.io/packages/source/i/img2pdf/img2pdf-0.3.6.tar.gz : 8cd5509a60b75f4442b897bad3d593e25ebd314105f3034a8f17def396a4a0fb
homepage   : https://gitlab.mister-muffin.de/josch/img2pdf
license    : LGPL-3.0-or-later
component  : multimedia.graphics
summary    : Losslessly convert raster images to PDF
description: |
    Python 3 library and command line utility img2pdf for losslessly converting a bunch of image files into a PDF file. That means that the images are either inserted into the PDF as-is or they are recompressed using lossless compression. Thus, img2pdf usually runs faster and may yield smaller PDF files than an ImageMagick convert command.
builddeps  :
    - python-pdfrw
    - python-pillow
rundeps    :
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -f $installdir/usr/bin/img2pdf-gui
check      : |
    %python3_test
